---
- name: install apache
  hosts: all
  become: true
  tasks:
   - yum:
      name: httpd
      state: present
   - name: start service
     service:
      name: httpd
      state: started
      enabled: true
